name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  
  build_v2:
    name: Build v2 Module
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Check out code
        uses: actions/checkout@v2

      - name: Change directory to v2
        run: cd v2

      - name: Get dependencies for v2 module
        run: go get -v -t -d ./...

      - name: Build v2 module
        run: go build -v ./...

      - name: Test v2 module
        run: go test -v ./...
