name: Release v2 on Tag

on:
  push:
    tags:
      - 'v*.*.*'   # Only trigger on version tags, e.g., v1.0.0

jobs:
  test_and_release_v2:
    name: Test and Release v2 Module
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.2'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Change directory to v2
        run: cd v2

      - name: Get dependencies for v2 module
        run: go get -v -t -d ./...

      - name: Run tests for v2 module
        run: go test -v ./...

      - name: Generate changelog
        id: changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref }}  # Use the tag as the release title
          tag_name: ${{ github.ref }}      # The pushed tag
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
